'use client';
import React, {useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,Download,Bell,CalendarDays,Check,ChevronRight,ClipboardList,Clock3,FlaskConical,Heart,Activity,Droplet,Footprints,HelpCircle,Hospital,House,MapPin,Megaphone,Menu,Minus,Pill,Plus,Search,Share2,ShieldCheck,ShoppingCart,Stethoscope,UserRound,Video,MessageCircle,Star,X,ShoppingBag} from 'lucide-react';
import './styles.css';

const doctors=[
 {name:'Dr. Ananya Nair',specialty:'General Physician',years:'5 yrs experience',rating:'4.8 (124)',fee:299,initials:'AN',tone:'rose',status:'Online'},
 {name:'Dr. Rahul Mehta',specialty:'Dermatologist',years:'8 yrs experience',rating:'4.9 (210)',fee:399,initials:'RM',tone:'blue',status:'Online'},
 {name:'Dr. Priya Menon',specialty:'Paediatrician',years:'6 yrs experience',rating:'4.7 (98)',fee:349,initials:'PM',tone:'pink',status:'Online'},
 {name:'Dr. Arjun S',specialty:'Cardiologist',years:'10 yrs experience',rating:'4.8 (164)',fee:499,initials:'AS',tone:'gold',status:'Online'}
];
const medicines=[
 {name:'Crocin 500mg',kind:'Strip of 15 tablets',price:25,old:30,tone:'blue',brand:'CRO'},
 {name:'Paracetamol 650mg',kind:'Strip of 10 tablets',price:18,old:22,tone:'green',brand:'MED'},
 {name:'Azithromycin 500mg',kind:'Strip of 3 tablets',price:45,old:52,tone:'red',brand:'AZI'},
 {name:'Cetirizine 10mg',kind:'Strip of 10 tablets',price:20,old:25,tone:'orange',brand:'CET'}
];
const tests=[
 {name:'Full Body Checkup',kind:'Includes 70+ tests',price:999,old:1999,tag:'Bestseller',icon:Stethoscope},
 {name:'Diabetes Checkup',kind:'Includes 3 tests',price:499,old:699,tag:'Popular',icon:ActivityIcon},
 {name:'Thyroid Profile',kind:'Includes 3 tests',price:299,old:499,tag:'',icon:FlaskConical},
 {name:'Vitamin D Test',kind:'Includes 1 test',price:699,old:899,tag:'',icon:Heart}
];
const clinics=[{name:'City Care Hospital',kind:'Multi-speciality',distance:'1.2 km',open:'Open 24/7',tone:'hospital'},{name:'Hope Clinic',kind:'General Clinic',distance:'2.4 km',open:'Open Now',tone:'clinic'},{name:'MediPlus Hospital',kind:'Multi-speciality',distance:'3.1 km',open:'Open 24/7',tone:'medical'}];
function ActivityIcon(props){return <ShieldCheck {...props}/>}
function Brand({purple=false}){return <img src={purple?"/curo-house-logo-r-purple.png":"/curo-house-logo-r.png"} alt="CURO HOUSE" className="logo-img"/>}
function Avatar({person,tone='rose',large=false}){return <div className={`avatar ${tone} ${large?'large':''}`} aria-hidden="true">{person.initials==='AN'?<img className="portrait-image" src="/doctor-portrait.png" alt=""/>:<><div className="avatar-hair"/><div className="avatar-face"><i/><i/><b/></div><div className="avatar-neck"/><div className="avatar-coat"/></>}<span>{person.initials}</span></div>}
function Topbar({title,onBack,actions}){return <header className="page-top"><button className="back-button" aria-label="Go back" onClick={onBack}><ArrowLeft/></button><strong>{title}</strong><div className="top-actions">{actions}</div></header>}
function App(){
 const [screen,setScreen]=useState('Home');const [menuOpen,setMenuOpen]=useState(false);
 const [modal,setModal]=useState({type:'welcome'});
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const [orderFilter,setOrderFilter]=useState('Medicines');const [cart,setCart]=useState(0);const [qty,setQty]=useState(1);const [selected,setSelected]=useState(null);const [activeTab,setActiveTab]=useState('About');const [notice,setNotice]=useState('');
 const go=(target,item)=>{if(item)setSelected(item);setScreen(target);setQuery('');setFilter('All');window.scrollTo({top:0,behavior:'smooth'})};
 const back=()=>{if(['DoctorDetail','MedicineDetail','TestDetail','HospitalDetail'].includes(screen))setScreen(({DoctorDetail:'Doctors',MedicineDetail:'Medicines',TestDetail:'Labs',HospitalDetail:'Hospitals'})[screen]);else setScreen('Home');window.scrollTo({top:0,behavior:'smooth'})};
 const toast=(s)=>{setNotice(s);setTimeout(()=>setNotice(''),2200)};
 const filteredDoctors=useMemo(()=>doctors.filter(x=>(x.name+' '+x.specialty).toLowerCase().includes(query.toLowerCase())&&(filter==='All'||x.specialty.toLowerCase().includes(filter.toLowerCase()))),[query,filter]);
 const filteredMedicines=useMemo(()=>medicines.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||(filter==='Pain Relief'&&x.name.includes('Crocin'))||(filter==='Vitamins'&&x.name.includes('Cetirizine'))||(filter==='Diabetes'&&x.name.includes('Paracetamol')))),[query,filter]);
 const filteredTests=useMemo(()=>tests.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())&&(filter==='All'||(filter==='Popular'&&x.tag)||(filter==='Full Body'&&x.name.includes('Full Body'))||(filter==='Diabetes'&&x.name.includes('Diabetes')))),[query,filter]);
 const appointment=(label)=>setModal({type:'confirm',title:'You’re all set',body:`Your ${label} selection is saved in this demo. No real booking or order has been placed.`});
 const navTo=(target)=>{setScreen(target);setQuery('');window.scrollTo({top:0,behavior:'smooth'})};
 const searchBox=(placeholder)=> <label className="searchbox"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder} aria-label={placeholder}/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X/></button>}</label>;
 const chips=(items)=> <div className="chips">{items.map(v=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{v}</button>)}</div>;
 const doctorRow=(d,compact=false)=><article className={'doctor-row-card '+(compact?'compact':'')} key={d.name} onClick={()=>go('DoctorDetail',d)}><Avatar person={d} tone={d.tone}/><div className="row-main"><span className="online"><i/>{d.status}</span><b>{d.name}</b><small>{d.specialty}</small><small>{d.years} <span>·</span> ★ {d.rating}</small>{compact&&<small>₹{d.fee} consultation fee</small>}</div><ChevronRight className="row-chevron"/></article>;
 const medicineRow=(m)=><article className="medicine-row" key={m.name}><button className={'packshot '+m.tone} onClick={()=>go('MedicineDetail',m)} aria-label={`View ${m.name}`}><span>{m.brand}</span><i/></button><div className="row-main" onClick={()=>go('MedicineDetail',m)}><b>{m.name}</b><small>{m.kind}</small><strong>₹{m.price} <del>₹{m.old}</del></strong></div><button className="small-primary" onClick={()=>{setCart(cart+1);toast(`${m.name} added to cart`)}}>Add</button></article>;
 const testRow=(t)=><article className="test-row" key={t.name} onClick={()=>go('TestDetail',t)}><div className="test-icon"><t.icon/></div><div className="row-main">{t.tag&&<span className="tag">{t.tag}</span>}<b>{t.name}</b><small>{t.kind}</small><strong>₹{t.price} <del>₹{t.old}</del></strong></div><button className="small-primary" onClick={e=>{e.stopPropagation();go('TestDetail',t)}}>Book</button></article>;
 const clinicRow=(c)=><article className="clinic-row" key={c.name} onClick={()=>go('HospitalDetail',c)}><div className={`building-thumb ${c.tone}`}><div className="building">✚</div></div><div className="row-main"><b>{c.name}</b><small>{c.kind}</small><small>{c.distance} <span>·</span> <em>{c.open}</em></small></div><ChevronRight className="row-chevron"/></article>;
 const showDoctorTab=['Doctors','DoctorDetail','Labs','TestDetail'].includes(screen);
 const navItems=showDoctorTab?[{label:'Home',icon:House,target:'Home'},{label:'Doctors',icon:Stethoscope,target:'Doctors'},{label:'Health',icon:Heart,target:'Health'},{label:'Profile',icon:UserRound,target:'Profile'}]:[{label:'Home',icon:House,target:'Home'},{label:'Orders',icon:ClipboardList,target:'Orders'},{label:'Health',icon:Heart,target:'Health'},{label:'Profile',icon:UserRound,target:'Profile'}];
 return <><main className="app-shell">
 {screen==='Home'?<><section className="hero"><header className="home-top"><Brand/><div className="top-actions"><button className="site-menu-toggle" aria-label={menuOpen?'Close navigation menu':'Open navigation menu'} aria-expanded={menuOpen} aria-controls="site-navigation-menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div></header>{menuOpen&&<nav id="site-navigation-menu" className="site-menu" aria-label="Website navigation"><div className="site-menu-account"><button onClick={()=>{setMenuOpen(false);setModal({type:'confirm',title:'Login coming soon',body:'Account access will be available when the CURO HOUSE platform launches.'})}}>Log in</button><button onClick={()=>{setMenuOpen(false);setModal({type:'confirm',title:'Sign up coming soon',body:'You’ll be able to create an account when the CURO HOUSE platform launches.'})}}>Sign up</button></div><span>EXPLORE</span><button onClick={()=>{setMenuOpen(false);go('Doctors')}}>Doctors</button><button onClick={()=>{setMenuOpen(false);go('Medicines')}}>Medicines</button><button onClick={()=>{setMenuOpen(false);go('Labs')}}>Lab tests</button><button onClick={()=>{setMenuOpen(false);go('Health')}}>Our services</button></nav>}<div className="hero-copy"><span>Healthcare</span><b>at Your Home</b></div><div className="hero-doctor"><div className="hero-halo"/><svg className="hero-sketch" viewBox="0 0 170 190" role="img" aria-label="Healthcare at home illustration"><path d="M36 166c4-25 10-43 27-51l20-9 18 9c17 8 24 28 29 51" fill="none" stroke="#eee7ff" strokeWidth="2.5" strokeLinecap="round"/><path d="M67 112l16 20 17-20M79 132l-8 30m11-30 9 30" fill="none" stroke="#cdb7fb" strokeWidth="2.2" strokeLinecap="round"/><path d="M83 20c-18 0-30 14-30 33v20c0 17 12 29 30 29s30-12 30-29V53c0-19-12-33-30-33Z" fill="none" stroke="#fff" strokeWidth="2.5"/><path d="M53 56c1-25 12-40 30-40 17 0 29 12 31 34-9-3-16-9-19-17-9 11-22 18-42 19Z" fill="none" stroke="#d7c8f6" strokeWidth="2.5" strokeLinejoin="round"/><path d="M71 59h1m23 0h1m-19 20c5 4 10 4 15 0" stroke="#fff" strokeWidth="2.5" strokeLinecap="round"/><path d="M53 60c-8 0-9 10-3 15m63-15c8 0 9 10 3 15" fill="none" stroke="#eee7ff" strokeWidth="2.2"/><path d="M53 133c-15 4-21 14-24 31m84-31c14 5 20 16 23 33" fill="none" stroke="#a98be7" strokeWidth="2" strokeLinecap="round"/><circle cx="83" cy="145" r="9" fill="#4d2092" stroke="#eee7ff" strokeWidth="2"/><path d="M83 140v10m-5-5h10" stroke="#fff" strokeWidth="1.8" strokeLinecap="round"/><path d="M125 28c0-8 10-12 15-5 5-7 15-3 15 5 0 7-15 18-15 18s-15-11-15-18Z" fill="#6b45a9" stroke="#e9e1fa" strokeWidth="1.6"/><path d="M126 89h22m-11-11v22" stroke="#cdb7fb" strokeWidth="2" strokeLinecap="round"/></svg></div></section>
 <section className="home-sheet"><label className="searchbox"><Search/><input placeholder="Search doctors, medicines, lab tests…" aria-label="Search doctors, medicines, lab tests" onFocus={()=>go('Doctors')}/></label>
 <div className="home-services"><button className="home-service lavender" onClick={()=>go('Doctors')}><span><Stethoscope/></span><b>Doctor<br/>Consultation</b><small>Talk to qualified doctors online</small><ChevronRight/></button><button className="home-service mint" onClick={()=>go('Medicines')}><span><Pill/></span><b>Medicine<br/>Delivery</b><small>Get medicines delivered to your home</small><ChevronRight/></button><button className="home-service sky" onClick={()=>go('Labs')}><span><FlaskConical/></span><b>Lab Tests</b><small>Book tests with home sample collection</small><ChevronRight/></button></div>
 <button className="home-medicine" onClick={()=>go('Medicines')}><div className="banner-pack-area"><div className="home-pack"><svg viewBox="0 0 160 100" role="img" aria-label="CURO HOUSE medicine delivery carton"><ellipse cx="98" cy="91" rx="53" ry="5" fill="#24103f" opacity=".12"/><path d="M4 61h25m-18 10h23m-15 10h18" fill="none" stroke="#4a218f" strokeWidth="3" strokeLinecap="round"/><path d="m43 35 39-21 62 13-39 22z" fill="#7044b2"/><path d="M43 35 105 49v40L43 75z" fill="#481c8d"/><path d="m105 49 39-22v41l-39 21z" fill="#35106d"/><path d="m43 35 62 14v8L43 43z" fill="#2d0c60"/><path d="m105 49 39-22v8l-39 22z" fill="#5c2c9c"/><path d="m55 32 27-14 49 10-27 16z" fill="#8056be" opacity=".82"/><path d="M105 49v40" stroke="#8c66c1" strokeWidth="1" opacity=".55"/></svg><img className="carton-logo" src="/curo-house-logo-r.png" alt="CURO HOUSE"/></div></div><div><b>Medicines delivered<br/>at your doorstep</b><small>Safe. Genuine. On time.</small></div><ChevronRight/></button>
 <section className="why-section"><div className="section-title"><h2>Why Choose Curo House?</h2></div><div className="why-grid"><div><span><ShieldCheck/></span>Trusted<br/>Healthcare</div><div><span><House/></span>Home<br/>Convenience</div><div><span><Stethoscope/></span>Verified<br/>Professionals</div><div><span><Heart/></span>Care for<br/>a Healthier You</div></div></section>
 <section className="home-following" aria-label="More from CURO HOUSE">
  <section className="expert-feature"><div className="feature-copy"><span className="eyebrow">EXPERT DOCTORS</span><h2>Your health,<br/>our priority.</h2><p>Connect with experienced doctors from the comfort of home.</p><button className="feature-cta" onClick={()=>go('Doctors')}>Find a doctor <ArrowRight/></button></div><div className="feature-art" aria-hidden="true"><div className="feature-orbit"/><div className="feature-card"><span><Stethoscope/></span><b>Care that<br/>comes home</b></div><Heart className="feature-heart"/><Plus className="feature-plus"/></div></section>
  <section className="reviews-section"><div className="lower-heading"><span className="eyebrow">A LITTLE MORE CARE</span><h2>Designed around you</h2><p>A few sample notes from our demo experience.</p></div><div className="review-track"><article className="review-card"><div className="review-stars" aria-label="5 out of 5 stars">★★★★★</div><p>“It feels simple to find the care I need, all in one place.”</p><div className="review-person"><span>AK</span><div><b>A sample patient</b><small>Kochi, Kerala</small></div></div></article><article className="review-card"><div className="review-stars" aria-label="5 out of 5 stars">★★★★★</div><p>“The medicine and lab services are easy to discover.”</p><div className="review-person"><span>RM</span><div><b>A sample patient</b><small>Ernakulam, Kerala</small></div></div></article><article className="review-card"><div className="review-stars" aria-label="5 out of 5 stars">★★★★★</div><p>“I can explore consultation options from home.”</p><div className="review-person"><span>SP</span><div><b>A sample patient</b><small>Thrissur, Kerala</small></div></div></article></div><small className="demo-caption">Illustrative feedback for this demo.</small></section>
  <section className="app-promo"><h2>“A healthier you”<br/>The app in your hand.</h2><button className="download-app-cta" onClick={()=>toast('The CURO HOUSE app is coming soon')}><span className="download-icon"><Download/></span><span>Download the app</span></button><div className="promo-device" role="img" aria-label="CURO HOUSE app preview on a smartphone"><div className="promo-device-screen"><div className="promo-notch"/><img src="/curo-house-logo-r.png" alt=""/><div className="promo-device-stores" aria-label="Coming soon to Google Play and the App Store"><svg viewBox="0 0 24 24" role="img" aria-label="Google Play"><path fill="#34a853" d="M3.5 2.7v18.6L13.7 12z"/><path fill="#4285f4" d="m13.7 12 3-3.1-9.2-5.3z"/><path fill="#fbbc04" d="m13.7 12-6.2 8.4 9.2-5.3z"/><path fill="#ea4335" d="m16.7 8.9 3.2 1.8c1 .6 1 2 0 2.6l-3.2 1.8-3-3.1z"/></svg><svg viewBox="0 0 24 24" role="img" aria-label="App Store"><path fill="currentColor" d="M16.7 12.8c0-2.1 1.7-3.1 1.8-3.2-1-1.5-2.6-1.7-3.2-1.7-1.4-.1-2.7.8-3.4.8-.7 0-1.8-.8-3-.8-1.5 0-2.9.9-3.7 2.2-1.6 2.8-.4 6.9 1.1 9.1.8 1.1 1.6 2.3 2.8 2.2 1.1 0 1.6-.7 3-.7s1.8.7 3 .7 2-.9 2.7-2.1a10 10 0 0 0 1.2-2.4c-.1 0-2.3-.9-2.3-4.1ZM14.5 6.5c.6-.7 1-1.7.9-2.7-.9 0-2 .6-2.6 1.3-.6.7-1.1 1.7-1 2.6 1 .1 2.1-.5 2.7-1.2Z"/></svg></div></div></div></section>

  <footer className="home-footer"><Brand purple/><p>Thoughtful healthcare, closer to home.</p><div className="footer-dropdowns"><details><summary>Privacy Policy <span aria-hidden="true">+</span></summary><p>This preview uses sample information only. Full privacy details will be available when CURO HOUSE launches.</p></details><details><summary>Terms of Use <span aria-hidden="true">+</span></summary><p>This website preview is for exploring the planned experience. It does not provide medical advice or place real orders.</p></details><details><summary>Contact &amp; Support <span aria-hidden="true">+</span></summary><p>Support contact details will be shared when the CURO HOUSE platform launches.</p></details></div><span className="copyright">© 2026 CURO HOUSE</span><span className="footer-launch">Main platform launching soon.</span></footer>
 </section>
 </section></>:null}
 {screen==='Doctors'?<><Topbar title="Doctors" onBack={back} actions={<><button aria-label="Notifications" onClick={()=>toast('You’re all caught up')}><Bell/></button><button aria-label="Appointments" onClick={()=>navTo('Orders')}><CalendarDays/></button></>}/><div className="screen-content">{searchBox('Search doctors or specialties…')}{chips(['All','General','Dermatology','Paediatrics','Cardiology'])}<div className="list-stack">{filteredDoctors.map(d=>doctorRow(d,true))}</div></div></>:null}
 {screen==='DoctorDetail'&&selected?<><Topbar title="" onBack={back} actions={<><button aria-label="Save doctor" onClick={()=>toast('Doctor saved')}><Heart/></button><button aria-label="Share doctor" onClick={()=>toast('Share link copied')}><Share2/></button></>}/><div className="detail-content"><section className="doctor-profile"><Avatar person={selected} tone={selected.tone} large/><div><h1>{selected.name}</h1><p>{selected.specialty}</p><div className="rating">★ <b>{selected.rating.split(' ')[0]}</b> ({selected.rating.match(/\((.*?)\)/)?.[1]} reviews)</div><small>♧ &nbsp;{selected.years}</small></div></section><div className="fee-line"><div><b>₹{selected.fee}</b><small>Consultation fee</small></div><button className="primary" onClick={()=>appointment('consultation')}>Book Now</button></div><div className="quick-actions"><div><Video/>Online<small>Available today</small></div><div><MessageCircle/>Video<small>Consultation</small></div><div><MessageCircle/>Chat<small>Support</small></div></div><div className="detail-tabs">{['About','Education','Reviews'].map(t=><button key={t} className={activeTab===t?'on':''} onClick={()=>setActiveTab(t)}>{t}</button>)}</div><h3>{activeTab==='About'?'About Doctor':activeTab}</h3><p className="detail-copy">{selected.name} is a dedicated {selected.specialty.toLowerCase()} with {selected.years} of experience in primary care. She believes in personalized treatment and patient education.</p><h3>Specialties</h3><div className="chips static"><span>Fever</span><span>Diabetes</span><span>Hypertension</span><span>Thyroid</span><span>General Health</span></div></div></>:null}
 {screen==='Medicines'?<><Topbar title="Medicines" onBack={back} actions={<button aria-label="Shopping cart" className="cart-button" onClick={()=>setModal({type:'cart'})}><ShoppingCart/>{cart>0&&<i>{cart}</i>}</button>}/><div className="screen-content">{searchBox('Search medicines…')}{chips(['All','Pain Relief','Vitamins','Diabetes'])}<div className="list-stack">{filteredMedicines.map(medicineRow)}</div></div>{cart>0&&<div className="cart-bar"><span>{cart} item{cart>1?'s':''} · ₹{cart*25}</span><button onClick={()=>setModal({type:'cart'})}>View Cart <ShoppingCart/></button></div>}</>:null}
 {screen==='MedicineDetail'&&selected?<><Topbar title="" onBack={back} actions={<button aria-label="Share medicine" onClick={()=>toast('Share link copied')}><Share2/></button>}/><div className="detail-content product-detail"><div className="product-stage"><div className="product-pack"><span>{selected.brand}</span><b>{selected.name.split(' ')[0]}</b><small>500 mg</small></div><div className="blister"/></div><div className="product-heading"><h1>{selected.name}</h1><span className="stock">In stock</span></div><p>{selected.kind}</p><div className="price"><b>₹{selected.price}</b><del>₹{selected.old}</del><span>17% off</span></div><small className="muted">GSK</small><h3>Description</h3><p className="detail-copy">This medicine is commonly used for relief from fever and mild to moderate pain. Follow the advice of a healthcare professional.</p><h3>Key Benefits</h3><ul className="benefits"><li>✓ &nbsp; Helps relieve pain</li><li>✓ &nbsp; May reduce fever</li><li>✓ &nbsp; Use as directed</li></ul><div className="purchase-bar"><div className="qty-control"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button>{qty}<button onClick={()=>setQty(qty+1)}><Plus/></button></div><button className="primary" onClick={()=>{setCart(cart+qty);toast('Added to cart')}}>Add to Cart</button></div></div></>:null}
 {screen==='Labs'?<><Topbar title="Lab Tests" onBack={back} actions={<button aria-label="Cart" onClick={()=>toast('Your test cart is empty')}><ShoppingCart/></button>}/><div className="screen-content">{searchBox('Search tests or packages…')}{chips(['All','Popular','Full Body','Diabetes'])}<div className="list-stack">{filteredTests.map(testRow)}</div></div></>:null}
 {screen==='TestDetail'&&selected?<><Topbar title="" onBack={back} actions={<button aria-label="Share test" onClick={()=>toast('Share link copied')}><Share2/></button>}/><div className="detail-content"><div className="test-hero"><FlaskConical/><span className="tag">{selected.tag||'Popular'}</span><i>✓</i></div><h1>{selected.name}</h1><p>{selected.kind}</p><div className="price"><b>₹{selected.price}</b><del>₹{selected.old}</del><span>50% off</span></div><h3>Includes</h3><ul className="benefits">{['Complete Blood Count (CBC)','Liver Function Test (LFT)','Kidney Function Test (KFT)','Lipid Profile','Thyroid Profile','Diabetes Screening','And much more…'].map(x=><li>✓ &nbsp; {x}</li>)}</ul><div className="purchase-bar"><button className="primary full" onClick={()=>appointment('home sample collection')}>Book Now</button></div></div></>:null}
 {screen==='Hospitals'?<><Topbar title="Hospitals & Clinics" onBack={back} actions={<button aria-label="Location" onClick={()=>toast('Showing care near Indiranagar')}><MapPin/></button>}/><div className="screen-content">{searchBox('Search hospitals or areas…')}{chips(['All','Nearby','Multi-speciality','Clinics'])}<div className="list-stack">{clinics.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).map(clinicRow)}</div></div></>:null}
 {screen==='HospitalDetail'&&selected?<><Topbar title="" onBack={back} actions={<button aria-label="Share hospital" onClick={()=>toast('Share link copied')}><Share2/></button>}/><div className="hospital-detail"><div className="hospital-hero"><div className="big-building"><b>✚</b><span/><span/><span/><span/><span/></div></div><div className="hospital-panel"><h1>{selected.name}</h1><p>{selected.kind}</p><div className="rating">★ <b>4.5</b> (320 reviews)</div><p className="hospital-meta"><MapPin/> {selected.distance} <i>·</i> <em>{selected.open}</em></p><div className="detail-tabs">{['Overview','Departments','Reviews'].map(t=><button key={t} className={activeTab===t?'on':''} onClick={()=>setActiveTab(t)}>{t}</button>)}</div><p className="detail-copy">A trusted multi-speciality hospital providing high-quality healthcare services with modern facilities and experienced doctors.</p><div className="hospital-services"><span>♙<small>Emergency</small></span><span>▣<small>Pharmacy</small></span><span>⌖<small>Parking</small></span></div><p className="hospital-meta"><MapPin/> 123 Health Street, Kochi, Kerala</p><button className="primary full" onClick={()=>toast('Directions are not available in this demo')}>Get Directions</button></div></div></>:null}
 {screen==='Orders'?<><Topbar title="My Orders" onBack={back}/><div className="screen-content order-screen"><div className="chips order-tabs" role="tablist" aria-label="Filter orders">{['Medicines','Lab Tests','Consultations'].map(t=><button key={t} role="tab" aria-selected={filter===(t==='Medicines'?'All':t)} className={orderFilter===t?'selected':''} onClick={()=>setOrderFilter(t)}>{t}</button>)}</div><div className="orders-intro"><div><h2>{orderFilter}</h2><p>Keep track of your care in one place.</p></div><span className="orders-count">1 order</span></div>{[{id:'#ORD12345',name:'Crocin 500mg',sub:'2 items · ₹125',state:'Delivered',date:'23 Sep 2026',type:'medicine'},{id:'#ORD12344',name:'Full Body Checkup',sub:'1 test · ₹999',state:'Scheduled',date:'25 Sep 2026',type:'test'},{id:'#ORD12343',name:'Dr. Ananya Nair',sub:'General consultation · ₹299',state:'Completed',date:'20 Sep 2026',type:'doctor'}].filter(o=>orderFilter==='Medicines'?o.type==='medicine':orderFilter==='Lab Tests'?o.type==='test':o.type==='doctor').map(o=><article key={o.id} className="order-card"><div className={`order-thumb ${o.type}`}>{o.type==='medicine'?<Pill/>:o.type==='test'?<FlaskConical/>:<Stethoscope/>}</div><div className="row-main"><small className="order-id">{o.id} <span>· {o.type==='medicine'?'Medicine':o.type==='test'?'Lab test':'Consultation'}</span></small><b>{o.name}</b><small>{o.sub}</small><div className="order-meta"><em className={`order-status ${o.state.toLowerCase()}`}>{o.state}</em><span>{o.date}</span></div></div><button className="view-button" aria-label={`View ${o.name}`} onClick={()=>setModal({type:'confirm',title:o.name,body:`${o.state} · ${o.date}. This is sample order information.`})}>View</button></article>)}</div></>:null}
 {screen==='Profile'?<><div className="profile-hero"><Topbar title="" onBack={back}/><div className="profile-person"><div className="user-icon large-user"><UserRound/></div><div><b>John Doe</b><small>john@example.com</small></div></div></div><div className="profile-menu">{[{label:'My Orders',icon:ClipboardList,target:'Orders'},{label:'My Appointments',icon:CalendarDays,target:'Orders'},{label:'Saved Items',icon:Heart,target:'Orders'},{label:'Notifications',icon:Bell,target:'Orders'},{label:'Help & Support',icon:HelpCircle,target:'Home'},{label:'About CURO HOUSE',icon:ShieldCheck,target:'Demo'}].map(({label,icon:Icon,target})=><button key={label} onClick={()=>target==='Demo'?setModal({type:'welcome'}):navTo(target)}><Icon/>{label}<ChevronRight/></button>)}<button className="logout" onClick={()=>toast('This is only a visual demo')}>Log Out</button></div></>:null}
 {screen==='Health'?<><Topbar title="My Health" onBack={back} actions={<button aria-label="Health reminders" onClick={()=>toast('No new reminders')}><Bell/></button>}/><div className="screen-content health-dashboard"><section className="health-summary"><div className="health-summary-head"><div><small>TODAY’S SNAPSHOT</small><h2>Your health data</h2></div><span>Sample data</span></div><div className="health-metrics"><article><span className="metric-icon bp"><Heart/></span><small>Blood pressure</small><b>118/78</b><em>mmHg</em></article><article><span className="metric-icon steps"><Footprints/></span><small>Steps today</small><b>6,240</b><em>of 8,000 goal</em></article><article><span className="metric-icon water"><Droplet/></span><small>Water today</small><b>5 / 8</b><em>glasses</em></article></div><p className="sample-note">Example values shown for the demo. Add your own records when the platform launches.</p></section><section className="health-section"><div className="health-section-head"><div><small>GENTLE REMINDERS</small><h2>Care for yourself</h2></div><button onClick={()=>toast('Your wellness reminders are up to date')}>See all <ChevronRight/></button></div><div className="wellness-list"><article><span className="wellness-icon water"><Droplet/></span><div><b>Keep water close</b><p>A glass of water can be a nice pause in your day.</p></div></article><article><span className="wellness-icon move"><Footprints/></span><div><b>Take a movement break</b><p>A short walk or stretch can help break up sitting time.</p></div></article><article><span className="wellness-icon rest"><Heart/></span><div><b>Make room to rest</b><p>A steady wind-down routine can support restful evenings.</p></div></article></div></section><section className="health-section records-section"><div className="health-section-head"><div><small>RECENT ACTIVITY</small><h2>Your health records</h2></div><button onClick={()=>navTo('Orders')}>View all <ChevronRight/></button></div><article className="record-card"><span><FlaskConical/></span><div><b>Full Body Checkup</b><small>Sample record · 20 Sep 2026</small></div><ChevronRight/></article><article className="record-card"><span><Stethoscope/></span><div><b>Doctor consultation</b><small>Sample record · 18 Sep 2026</small></div><ChevronRight/></article><p className="sample-note">This sample profile is for demonstration only and is not medical advice.</p></section></div></>:null}
 </main><nav className="bottom-nav" aria-label="Main navigation">{navItems.map(({label,icon:Icon,target})=><button className={(screen===target||(['DoctorDetail','TestDetail'].includes(screen)&&target==='Doctors'))?'active':''} key={label} onClick={()=>navTo(target)}><Icon/><span>{label}</span></button>)}</nav>
 {notice&&<div className="toast"><Check/>{notice}</div>}{modal&&<div className="modal-backdrop"><section className="demo-modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title">{modal.type==='welcome'?<><span className="welcome-icon"><Megaphone/></span><h2 id="dialog-title">This is a Demo</h2><p>Welcome to CURO HOUSE.<br/><br/>You’re viewing a preview of the experience. Our main platform is launching soon.</p><button className="primary full" onClick={()=>setModal(null)}>Continue</button></>:modal.type==='cart'?<><button className="close" onClick={()=>setModal(null)} aria-label="Close"><X/></button><span className="welcome-icon"><ShoppingBag/></span><h2 id="dialog-title">Your Cart</h2><p>{cart?`${cart} item${cart>1?'s':''} added · Estimated total ₹${cart*25}`:'Your cart is empty. Add an item to see it here.'}</p><button className="primary full" onClick={()=>{setModal(null);if(cart)appointment('medicine order')}}>{cart?'Continue':'Continue browsing'}</button></>:<><button className="close" onClick={()=>setModal(null)} aria-label="Close"><X/></button><span className="welcome-icon"><Check/></span><h2 id="dialog-title">{modal.title}</h2><p>{modal.body}</p><button className="primary full" onClick={()=>setModal(null)}>Got it</button></>}<small>{modal.type==='welcome'?'Preview only · Main platform launching soon.':'No real booking, payment or order has been made.'}</small></section></div>}</>;
}

export default App;
